#pragma once

#define PCB_REV 11
#define ENABLE_OPT_NOINLINE  0
#define ENABLE_OPT_ASSEMBLER 0

#define FW_HARDWARE_TESTER   0
#define FW_CALCULATOR_HP35   0
#define FW_CALCULATOR_HP21   0
#define FW_TOTP_AUTHENTICATE 1
