#pragma once

#define PCB_REV 10
#define ENABLE_OPT_NOINLINE  0
#define ENABLE_OPT_ASSEMBLER 0

//#define FW_HARDWARE_TESTER
//#define FW_CALCULATOR_NATIVE
#define FW_CALCULATOR_HP35
//#define FW_CALCULATOR_HP21
